import { describe,expect,it } from "vitest";
import { assetOptionLabel,canAdministerAssets,canEmployeeCancelAssetRequest,isAssetAvailable,isLowStock,itemsForCategory,nonNegativeQuantity,requestNeedsExistingAsset,requestCode,supportsPhysicalAssets } from "@/lib/assets/workflow";

describe("Assets & Supplies permission and workflow rules",()=>{
  it("allows only explicit administrator access levels to administer assets",()=>{
    expect(canAdministerAssets("Finance Admin")).toBe(true);expect(canAdministerAssets("Super Admin")).toBe(true);expect(canAdministerAssets("Admin")).toBe(true);
    expect(canAdministerAssets("Manager")).toBe(false);expect(canAdministerAssets("Employee")).toBe(false);
  });
  it("lets employees cancel only pending requests",()=>{expect(canEmployeeCancelAssetRequest("pending_approval")).toBe(true);expect(canEmployeeCancelAssetRequest("approved")).toBe(false);expect(canEmployeeCancelAssetRequest("issued")).toBe(false);});
  it("flags stock at or below the configured minimum",()=>{expect(isLowStock({stock_tracked:true,current_stock:3,minimum_stock_level:3})).toBe(true);expect(isLowStock({stock_tracked:true,current_stock:4,minimum_stock_level:3})).toBe(false);expect(isLowStock({stock_tracked:false,current_stock:0,minimum_stock_level:2})).toBe(false);});
  it("filters dependent item options by category and active state",()=>{const items=[{id:"1",category_id:"it",active:true},{id:"2",category_id:"office",active:true},{id:"3",category_id:"it",active:false}];expect(itemsForCategory(items,"it").map(i=>i.id)).toEqual(["1"]);});
  it("recognizes request types that support existing asset linkage",()=>{expect(requestNeedsExistingAsset("replacement")).toBe(true);expect(requestNeedsExistingAsset("repair")).toBe(true);expect(requestNeedsExistingAsset("lost_damaged_replacement")).toBe(true);expect(requestNeedsExistingAsset("consumable")).toBe(false);});
  it("normalizes request quantities safely",()=>{expect(nonNegativeQuantity(3)).toBe(3);expect(nonNegativeQuantity(-1)).toBe(1);expect(nonNegativeQuantity("bad",2)).toBe(2);});
  it("formats traceable request references",()=>expect(requestCode(42)).toBe("AR-000042"));
  it("recognizes durable assets as physical assets",()=>expect(supportsPhysicalAssets({item_type:"durable_asset"})).toBe(true));
  it("recognizes explicitly individual catalogue items",()=>expect(supportsPhysicalAssets({item_type:"accessory",individually_tracked:true})).toBe(true));
  it("does not treat quantity stock as a physical asset",()=>expect(supportsPhysicalAssets({item_type:"consumable",individually_tracked:false})).toBe(false));
  it("marks only active available assets as assignable",()=>expect(isAssetAvailable({active:true,status:"available",item:{active:true}})).toBe(true));
  it("excludes inactive assets from availability",()=>expect(isAssetAvailable({active:false,status:"available",item:{active:true}})).toBe(false));
  it("excludes assets for inactive catalogue items",()=>expect(isAssetAvailable({active:true,status:"available",item:{active:false}})).toBe(false));
  it("excludes assigned asset statuses",()=>expect(isAssetAvailable({active:true,status:"assigned",item:{active:true}})).toBe(false));
  it("excludes assets with active ownership records",()=>expect(isAssetAvailable({active:true,status:"available",item:{active:true}},new Set(["a1"]),"a1")).toBe(false));
  it("builds a human-readable asset option label",()=>expect(assetOptionLabel({item:{name:"Laptop"},brand:"Dell",model:"Latitude",asset_tag:"LT-01",serial_number:"SN-99"})).toBe("Laptop — Dell Latitude — LT-01 — SN-99"));
  it("uses safe fallbacks in asset option labels",()=>expect(assetOptionLabel({item:{name:"Mouse"}})).toBe("Mouse — Unspecified brand/model — No tag — No serial"));
});

describe("Assets module implementation contracts",()=>{
  it("keeps employee ownership and history in the migration",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("asset_assignments_one_active_idx");expect(source).toContain("asset_request_history");expect(source).toContain("inventory_transactions");expect(source).toContain("asset_audit_log");expect(source).toContain("employee_id=public.get_my_employee_id()");});
  it("seeds centrally managed IT and stationery catalogues",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("Headset Replacement");expect(source).toContain("Mouse Wire Replacement");expect(source).toContain("ID Card Replacement");expect(source).toContain("Other Stationery / Supply");});
  it("server-enforces administration and scoped employee reads",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain("canAdministerAssets(context.profile.role)");expect(source).toContain('.eq("employee_id",employeeId)');expect(source).toContain("Asset administrator access required");});
  it("issues quantity inventory and durable assignments through distinct paths",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('transaction_type:"issue"');expect(source).toContain('asset_assignments").insert');expect(source).toContain('status:"replaced"');});
  it("reuses Kairo shared email infrastructure",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/lib/assets/notifications.ts","utf8"));expect(source).toContain("sendEmail");expect(source).toContain("KAIRO_SENDER_NAME");expect(source).toContain("createDespachoLogoAttachment");});
  it("exposes employee-only asset, request, and request-item tabs",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));expect(source).toContain('id: "my_assets"');expect(source).toContain('id: "my_requests"');expect(source).toContain('id: "request_item"');});
  it("exposes the complete administrator workspace",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));for(const tab of ['id: "dashboard"','id: "assigned"','id: "requests"','id: "inventory"','id: "settings"'])expect(source).toContain(tab);});
  it("supports durable asset creation and assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="create_and_assign_asset"');expect(source).toContain('status:"assigned"');});
  it("preserves an active ownership record for future exit clearance",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("asset_assignments_employee_idx");expect(source).toContain("where status='assigned'");});
  it("protects business-critical request statuses with a database constraint",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("'pending_approval','approved','rejected','awaiting_issue','issued','cancelled','under_repair','completed'");});
  it("supports ID-card deactivation traceability",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("previous_id_deactivated");expect(source).toContain("ID Card Replacement");});
  it("records returns without deleting the original assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="return_asset"');expect(source).toContain('returned_date');expect(source).not.toContain('from("asset_assignments").delete()');});
  it("prevents stock from being issued below zero",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain("Insufficient stock");expect(source).toContain("Stock cannot become negative");});
  it("notifies administrators on creation and employees on decisions",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/lib/assets/notifications.ts","utf8"));expect(source).toContain('input.type==="created"');expect(source).toContain('type AssetEvent="created"|"approved"|"rejected"|"issued"');});
  it("mounts Assets inside Workforce rather than as a sidebar module",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/(app)/team/page.tsx","utf8"));expect(source).toContain('tab === "assets"');expect(source).toContain("<AssetsWorkspace/>");});
  it("does not place Assign Asset in the workspace hero",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));const hero=source.slice(source.indexOf("Workforce operations"),source.indexOf("function Card"));expect(hero).not.toContain("+ Assign Asset");});
  it("loads admin assignment records only after search",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('view==="assignments"');expect(source).toContain('params.get("searched")!=="true"');});
  it("loads admin requests only after search",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('view==="requests"');expect(source.match(/params\.get\("searched"\)!=="true"/g)?.length).toBe(2);});
  it("supports all requested request filters on the server",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));for(const filter of ["employeeId","categoryId","itemId","requestTypeId","status","requestedFrom","requestedTo"])expect(source).toContain(`params.get("${filter}")`);});
  it("has distinct catalogue and physical asset creation workflows",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));expect(source).toContain("+ Add Item");expect(source).toContain("+ Add Physical Asset");expect(source).toContain('action: "create_asset"');});
  it("supports item edit and soft deactivation",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="save_item"');expect(source).toContain('action==="deactivate_item"');expect(source).toContain('active:false');});
  it("supports physical asset update and retirement audit",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="update_asset"');expect(source).toContain('"ASSET_RETIRED"');expect(source).toContain('"ASSET_UPDATED"');});
  it("stores assignment expected return dates",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain("expected_return_date");});
  it("adds only focused inventory metadata in the reconciliation migration",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608220001_assets_inventory_management.sql","utf8"));expect(source).toContain("warranty_expiry");expect(source).toContain("expected_return_date");expect(source).toContain("assets_available_item_idx");expect(source).not.toContain("create table");});
  it("keeps a unique active assignment guard",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("asset_assignments_one_active_idx");});
  it("uses active employees in assignment administration",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('.eq("status","active").order("employee_code")');});
});
