import { describe,expect,it } from "vitest";
import { canAdministerAssets,canEmployeeCancelAssetRequest,isLowStock,itemsForCategory,nonNegativeQuantity,requestNeedsExistingAsset,requestCode } from "@/lib/assets/workflow";

describe("Assets & Supplies permission and workflow rules",()=>{
  it("allows only explicit administrator access levels to administer assets",()=>{
    expect(canAdministerAssets("Finance Admin")).toBe(true);expect(canAdministerAssets("Super Admin")).toBe(true);expect(canAdministerAssets("Admin")).toBe(true);
    expect(canAdministerAssets("Manager")).toBe(false);expect(canAdministerAssets("Employee")).toBe(false);
  });
  it("lets employees cancel only pending requests",()=>{expect(canEmployeeCancelAssetRequest("pending_approval")).toBe(true);expect(canEmployeeCancelAssetRequest("approved")).toBe(false);expect(canEmployeeCancelAssetRequest("issued")).toBe(false);});
  it("flags stock at or below the configured minimum",()=>{expect(isLowStock({stock_tracked:true,current_stock:3,minimum_stock_level:3})).toBe(true);expect(isLowStock({stock_tracked:true,current_stock:4,minimum_stock_level:3})).toBe(false);expect(isLowStock({stock_tracked:false,current_stock:0,minimum_stock_level:2})).toBe(false);});
  it("filters dependent item options by category and active state",()=>{const items=[{id:"1",category_id:"it",active:true},{id:"2",category_id:"office",active:true},{id:"3",category_id:"it",active:false}];expect(itemsForCategory(items,"it").map(i=>i.id)).toEqual(["1"]);});
  it("recognizes request types that support existing asset linkage",()=>{expect(requestNeedsExistingAsset("replacement")).toBe(true);expect(requestNeedsExistingAsset("repair")).toBe(true);expect(requestNeedsExistingAsset("lost_damaged_replacement")).toBe(true);expect(requestNeedsExistingAsset("consumable")).toBe(false);});
  it("normalizes request quantities safely",()=>{expect(nonNegativeQuantity(3)).toBe(3);expect(nonNegativeQuantity(-1)).toBe(1);expect(nonNegativeQuantity("bad",2)).toBe(2);});
  it("formats traceable request references",()=>expect(requestCode(42)).toBe("AR-000042"));
});

describe("Assets module implementation contracts",()=>{
  it("keeps employee ownership and history in the migration",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("asset_assignments_one_active_idx");expect(source).toContain("asset_request_history");expect(source).toContain("inventory_transactions");expect(source).toContain("asset_audit_log");expect(source).toContain("employee_id=public.get_my_employee_id()");});
  it("seeds centrally managed IT and stationery catalogues",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("Headset Replacement");expect(source).toContain("Mouse Wire Replacement");expect(source).toContain("ID Card Replacement");expect(source).toContain("Other Stationery / Supply");});
  it("server-enforces administration and scoped employee reads",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain("canAdministerAssets(context.profile.role)");expect(source).toContain('.eq("employee_id",employeeId)');expect(source).toContain("Asset administrator access required");});
  it("issues quantity inventory and durable assignments through distinct paths",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('transaction_type:"issue"');expect(source).toContain('asset_assignments").insert');expect(source).toContain('status:"replaced"');});
  it("reuses Kairo shared email infrastructure",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/lib/assets/notifications.ts","utf8"));expect(source).toContain("sendEmail");expect(source).toContain("KAIRO_SENDER_NAME");expect(source).toContain("createDespachoLogoAttachment");});
  it("exposes employee-only asset, request, and request-item tabs",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));expect(source).toContain('id:"my_assets"');expect(source).toContain('id:"my_requests"');expect(source).toContain('id:"request_item"');});
  it("exposes the complete administrator workspace",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/components/assets/AssetsWorkspace.tsx","utf8"));for(const tab of ['id:"dashboard"','id:"assigned"','id:"requests"','id:"inventory"','id:"settings"'])expect(source).toContain(tab);});
  it("supports durable asset creation and assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="create_and_assign_asset"');expect(source).toContain('status:"assigned"');});
  it("preserves an active ownership record for future exit clearance",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("asset_assignments_employee_idx");expect(source).toContain("where status='assigned'");});
  it("protects business-critical request statuses with a database constraint",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("'pending_approval','approved','rejected','awaiting_issue','issued','cancelled','under_repair','completed'");});
  it("supports ID-card deactivation traceability",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("supabase/migrations/202608200003_assets_and_supplies.sql","utf8"));expect(source).toContain("previous_id_deactivated");expect(source).toContain("ID Card Replacement");});
  it("records returns without deleting the original assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain('action==="return_asset"');expect(source).toContain('returned_date');expect(source).not.toContain('from("asset_assignments").delete()');});
  it("prevents stock from being issued below zero",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/api/assets/route.ts","utf8"));expect(source).toContain("Insufficient stock");expect(source).toContain("Stock cannot become negative");});
  it("notifies administrators on creation and employees on decisions",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/lib/assets/notifications.ts","utf8"));expect(source).toContain('input.type==="created"');expect(source).toContain('type AssetEvent="created"|"approved"|"rejected"|"issued"');});
  it("mounts Assets inside Workforce rather than as a sidebar module",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile("src/app/(app)/team/page.tsx","utf8"));expect(source).toContain('tab === "assets"');expect(source).toContain("<AssetsWorkspace/>");});
});
