import { readFileSync } from "node:fs";import {describe,expect,it} from "vitest";
const source=(path:string)=>readFileSync(path,"utf8");
describe("performance module contracts",()=>{
  const migration=source("supabase/migrations/202608130002_performance_reviews.sql");const server=source("src/lib/performance/server.ts");
  it("keeps Reviews inside Workforce with the required navigation",()=>{const page=source("src/app/(app)/team/page.tsx");for(const label of ["Overview","Profile Approvals","Organization Chart","Reviews","Assets","Exit Process","Policies"])expect(page).toContain(`label: "${label}"`);expect(page).toContain("<ReviewsWorkspace");});
  it("uses authoritative billable project classification",()=>{expect(server).toContain('projects!inner(is_billable)');expect(server).toContain('.eq("projects.is_billable",true)');});
  it("enforces administrator, manager, and employee scope server-side",()=>{expect(server).toContain("hasSuperAdminAccess");expect(server).toContain('actor.role==="manager"');expect(server).toContain('actor.role==="employee"');expect(migration).toContain("reporting_manager_id=public.get_my_employee_id()");});
  it("protects finalized history and requires a reopen reason",()=>{expect(server).toContain('status==="finalized"');expect(server).toContain("snapshot={employee");expect(server).toContain("mandatory reopen reason");expect(migration).toContain("snapshot jsonb");});
  it("audits policies, metrics, events, comments and workflow",()=>{for(const action of ["performance_event_added","performance_event_updated","performance_event_deleted","performance_metric_added","performance_metric_updated","performance_metric_deleted","utilization_policy_changed","performance_comment_added","review_status_changed","review_finalized","review_reopened"])expect(server).toContain(action);expect(migration).toContain("performance_audit_log");});
  it("shows live self performance before review finalization without broadening employee scope",()=>{expect(server).toContain('actor.role==="employee") query=query.eq("id",actor.employeeId)');expect(server).toContain("const reviews=allReviews");expect(server).toContain("calculatePerformance");});
  it("reuses centralized employee PDF protection without persisting passwords",()=>{const report=source("src/app/api/performance/report/[id]/route.ts");expect(report).toContain("protectEmployeePdf");expect(report).toContain('documentType:"performance"');expect(migration).not.toMatch(/pdf_password|generated_password|password\s+text/i);});
  it("leaves existing Payslip and YTD documents untouched",()=>{expect(source("src/components/payroll/PayslipPdfDocument.tsx")).toContain("PayslipPdfDocument");expect(source("src/components/payroll/YtdPayrollPdfDocument.tsx")).toContain("YtdPayrollPdfDocument");});
  it("renders My Review for every role and role-specific management workspaces",()=>{const workspace=source("src/components/performance/ReviewsWorkspace.tsx");expect(workspace).toContain('return [["my_review","My Review"],["recognition","Recognition"]]');expect(workspace).toContain('return [["dashboard","Dashboard"],["my_review","My Review"],["reviews","Team Reviews"]');expect(workspace).toContain('return [["dashboard","Dashboard"],["my_review","My Review"],["reviews","Annual Reviews"]');expect(workspace).toContain('employeeScope={data.employeeId}');expect(workspace).toContain('"Recognition & Penalties"');expect(workspace).not.toContain("Goals & KPIs");});
  it("allows scoped annual report downloads before a review starts",()=>{const live=source("src/app/api/performance/report/live/route.ts");expect(live).toContain("loadPerformance");expect(live).toContain('actor.role!=="admin"');expect(live).toContain('actor.role==="manager"');expect(live).toContain("protectEmployeePdf");});
  it("uses performance events as the operational source of truth and snapshots references",()=>{const redesign=source("supabase/migrations/202608130004_performance_management_redesign.sql");expect(redesign).toContain("performance_events_source_unique_idx");expect(redesign).toContain("performance_settings");expect(server).toContain("eventReferences");expect(server).toContain("policyVersion");expect(server).not.toContain("events:data.events.filter");});
  it("synchronizes finalized payroll LOP and prevents editing automatic events",()=>{expect(server).toContain("syncPayrollLopEvents");expect(server).toContain('.in("status",["approved","locked","published"])');expect(server).toContain('source_type:"payroll"');expect(server).toContain("Payroll-synchronized LOP events cannot be edited manually");});
});
