import { describe, expect, it } from "vitest";
import { calculatePerformance, DEFAULT_UTILIZATION_POLICIES, performanceCategory, policyForLevel } from "../src/lib/performance/calculation";
import type { PerformanceEvent, PerformanceMetric } from "../src/lib/performance/types";
const metrics:PerformanceMetric[]=[
  ["feedback","Client Feedback","client_feedback","booster",5,true], ["scale","Client Scale-up","client_scale_up","booster",10,true], ["testimonial","Client Testimonial","client_testimonial","booster",10,true], ["referral","Client Referral","client_referral","booster",20,true], ["rockstar","Rockstar Award","rockstar_award","booster",12,false], ["action","Non-disciplinary Action","non_disciplinary_action","penalty",5,false], ["escalation","Client Escalation","client_escalation","penalty",10,true], ["refund","Refund","refund","penalty",10,true],
].map(([id,name,code,category,score,client],index)=>({id:String(id),name:String(name),code:String(code),category:category as "booster"|"penalty",default_score_delta:Number(score),requires_client:Boolean(client),active:true,display_order:index,core_metric:true,qualification_rules:{}}));
let sequence=0;const event=(code:string,options:Partial<PerformanceEvent>={}):PerformanceEvent=>{const metric=metrics.find(item=>item.code===code)!;sequence+=1;return {id:`e${sequence}`,employee_id:"employee",performance_year:2026,metric_id:metric.id,client_id:"client-1",event_date:`2026-01-${String(sequence).padStart(2,"0")}`,description:code,qualification_status:"qualified",score_delta:metric.default_score_delta,evidence_url:null,notes:null,created_by:null,created_at:"",metric,...options};};
const calculate=(hours:number[],events:PerformanceEvent[]=[],level="Level 3")=>calculatePerformance({policy:policyForLevel(level),monthlyBillableHours:hours,events,metrics,reviewFinalized:true});
describe("performance calculation engine",()=>{
  it("uses billable-hour input without any total/non-billable input",()=>{const result=calculate(Array(12).fill(105));expect(result.annualActual).toBe(1260);expect(result.utilizationPercent).toBeCloseTo(77.7778);expect(calculatePerformance.toString()).not.toContain("totalHours");});
  it("selects Level 1, Level 2, and Level 3+ policies",()=>{expect(policyForLevel("Level 1").annual_expected_hours).toBe(1080);expect(policyForLevel("Level 2").annual_expected_hours).toBe(1440);expect(policyForLevel("Level 7").annual_expected_hours).toBe(1620);expect(DEFAULT_UTILIZATION_POLICIES).toHaveLength(3);});
  it("calculates monthly, quarterly and annual utilization with annual utilization as base score",()=>{const result=calculate(Array(12).fill(135));expect(result.monthly[0].percent).toBe(100);expect(result.quarterly[0]).toMatchObject({expected:405,actual:405,percent:100});expect(result.utilizationPercent).toBe(100);expect(result.overallScore).toBe(100);});
  it("scores one feedback per client but separately across clients",()=>{const same=[event("client_feedback"),event("client_feedback")];expect(calculate(Array(12).fill(135),same).boosterScore).toBe(5);const different=[event("client_feedback",{client_id:"a"}),event("client_feedback",{client_id:"b"})];expect(calculate(Array(12).fill(135),different).boosterScore).toBe(10);});
  it("scores scale-ups, qualified/non-qualified testimonials, referrals and configured Rockstar",()=>{const result=calculate(Array(12).fill(135),[event("client_scale_up"),event("client_testimonial",{client_id:"t"}),event("client_testimonial",{client_id:"n",qualification_status:"not_qualified"}),event("client_referral"),event("rockstar_award")]);expect(result.boosterScore).toBe(10+10+5+20+12);});
  it("scores actions, escalations and refunds as penalties",()=>{const result=calculate(Array(12).fill(135),[event("non_disciplinary_action"),event("client_escalation"),event("refund")]);expect(result.penaltyScore).toBe(25);expect(result.overallScore).toBe(75);});
  it("applies escalation ineligibility and critical thresholds without changing employment data",()=>{const escalations=Array.from({length:5},()=>event("client_escalation"));const result=calculate(Array(12).fill(135),escalations);expect(result.eligibility).toBe("not_eligible");expect(result.eligibilityReasons.join(" ")).toMatch(/Three or more/);expect(result.criticalFlags[0]).toMatch(/5 or more/);expect(result).not.toHaveProperty("employmentStatus");});
  it("flags three qualifying refunds",()=>{const result=calculate(Array(12).fill(135),Array.from({length:3},()=>event("refund")));expect(result.criticalFlags[0]).toMatch(/3 or more qualifying client refunds/);});
  it("makes below-minimum utilization and scores below 80 ineligible",()=>{const result=calculate(Array(12).fill(50));expect(result.eligibility).toBe("not_eligible");expect(result.eligibilityReasons).toHaveLength(2);});
  it("uses exact performance category boundaries",()=>{expect(performanceCategory(79.99)).toBe("Not Eligible for Evaluation");expect(performanceCategory(80)).toBe("Partially Met Expectations");expect(performanceCategory(100)).toBe("Met Expectations");expect(performanceCategory(125)).toBe("Exceeded Expectations");expect(performanceCategory(150)).toBe("Substantially Exceeded Expectations");});
});
