import { createElement, type ReactElement } from "react";
import { renderToBuffer, type DocumentProps } from "@react-pdf/renderer";
import { PerformanceReportPdf } from "@/components/performance/PerformanceReportPdf";
import { loadCompanyLogo, loadCompanySettings } from "@/lib/settings/companySettings";
import { performanceActor } from "@/lib/performance/server";
import { protectPayslipPdf } from "@/lib/payroll/payslipPdf";
import { payslipPassword } from "@/lib/payroll/password";
import { hasSuperAdminAccess } from "@/lib/roles";
import type { PerformanceCalculation, PerformanceEmployee, PerformanceEvent } from "@/lib/performance/types";
export async function GET(request:Request,context:{params:Promise<{id:string}>}){try{const actor=await performanceActor(request);const {id}=await context.params;const review=await actor.admin.from("performance_reviews").select("*").eq("id",id).single();if(review.error||review.data.status!=="finalized"||!review.data.snapshot)throw new Error("Finalized performance report not found");const employee=await actor.admin.from("employees").select("id,employee_code,name,department,role,level,reporting_manager_id,date_of_joining,date_of_birth,status").eq("id",review.data.employee_id).single();if(employee.error)throw new Error(employee.error.message);if(!hasSuperAdminAccess(actor.role)&&actor.employeeId!==employee.data.id){const allowed=actor.role==="manager"&&employee.data.reporting_manager_id===actor.employeeId;if(!allowed)throw new Error("Forbidden");}const manager=employee.data.reporting_manager_id?await actor.admin.from("employees").select("id,name").eq("id",employee.data.reporting_manager_id).maybeSingle():{data:null,error:null};const company=await loadCompanySettings(actor.admin);const logo=await loadCompanyLogo({...company,invoice_logo_url:"/despacho-logo-full.png"});const snapshot=review.data.snapshot as {employee?:PerformanceEmployee;calculation:PerformanceCalculation;events:PerformanceEvent[];comments:Array<{comment_type:string;comment:string}>};const employeeDetails={...(snapshot.employee||employee.data),reporting_manager:snapshot.employee?.reporting_manager||manager.data||null} as PerformanceEmployee;const document=createElement(PerformanceReportPdf,{logoSrc:logo.dataUrl,year:review.data.performance_year,employee:employeeDetails,calculation:snapshot.calculation,events:snapshot.events||[],comments:snapshot.comments||[]}) as ReactElement<DocumentProps>;const pdf=await renderToBuffer(document);const settings=await actor.admin.from("payroll_settings").select("payslip_password_rule").eq("singleton_key",true).single();if(settings.error)throw new Error(settings.error.message);const password=payslipPassword(settings.data.payslip_password_rule,employee.data.employee_code||"",employee.data.date_of_birth);const protectedPdf=await protectPayslipPdf(pdf,password);return new Response(new Uint8Array(protectedPdf),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="Performance_Report_${employee.data.employee_code}_${review.data.performance_year}.pdf"`,"Cache-Control":"private, no-store"}});}catch(cause){const message=cause instanceof Error?cause.message:"Unable to generate performance report";return Response.json({error:message},{status:message==="Unauthorized"?401:400});}}
