import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { hasSuperAdminAccess, normalizeRole } from "@/lib/roles";
import { calculatePerformance, policyForLevel } from "./calculation";
import type { PerformanceData, PerformanceEmployee, PerformanceEvent, PerformanceMetric, PerformanceReview, PerformanceSettings, UtilizationPolicy } from "./types";

type Actor = { admin: SupabaseClient; userId: string; employeeId: string; role: string; name: string };
export async function performanceActor(request: Request): Promise<Actor> {
  const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
  if(!token||!url||!key) throw new Error("Unauthorized");
  const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
  const user=await admin.auth.getUser(token); if(user.error||!user.data.user) throw new Error("Unauthorized");
  const profile=await admin.from("profiles").select("employee_id,role,full_name").eq("user_id",user.data.user.id).single();
  if(profile.error||!profile.data?.employee_id) throw new Error("Performance profile is not configured");
  return {admin,userId:user.data.user.id,employeeId:profile.data.employee_id,role:normalizeRole(profile.data.role),name:profile.data.full_name||"User"};
}
export const performanceAdmin = (role:string) => { if(!hasSuperAdminAccess(role)) throw new Error("Super Admin or Finance Admin access required"); };

async function audit(actor:Actor,input:{action:string;reviewId?:string;employeeId?:string;year?:number;metricId?:string;eventId?:string;reason?:string;previous?:unknown;next?:unknown}) {
  const result=await actor.admin.from("performance_audit_log").insert({review_id:input.reviewId||null,employee_id:input.employeeId||null,performance_year:input.year||null,metric_id:input.metricId||null,event_id:input.eventId||null,action:input.action,actor_user_id:actor.userId,actor_role:actor.role,reason:input.reason||null,previous_value:input.previous||null,new_value:input.next||null});
  if(result.error) throw new Error(result.error.message);
}
const validYear=(value:unknown)=>{const year=Number(value);if(!Number.isInteger(year)||year<2000||year>2200)throw new Error("Select a valid performance year");return year;};

type BillableTimeEntry = {
  id: string;
  employee_id: string;
  entry_date: string;
  hours: number | null;
};

async function loadAllBillableTimeEntries(actor:Actor,year:number,employeeIds:string[]){
  if(!employeeIds.length)return {data:[] as BillableTimeEntry[],error:null};
  const pageSize=1000;const data:BillableTimeEntry[]=[];
  for(let from=0;;from+=pageSize){
    const page=await actor.admin.from("time_entries")
      .select("id,employee_id,entry_date,hours,projects!inner(is_billable)")
      .gte("entry_date",`${year}-01-01`).lte("entry_date",`${year}-12-31`)
      .in("employee_id",employeeIds).eq("projects.is_billable",true)
      .order("entry_date",{ascending:true}).order("id",{ascending:true})
      .range(from,from+pageSize-1);
    if(page.error)return {data,error:page.error};
    const rows=(page.data||[]) as unknown as BillableTimeEntry[];data.push(...rows);
    if(rows.length<pageSize)break;
  }
  return {data,error:null};
}

async function visibleEmployees(actor:Actor) {
  let query=actor.admin.from("employees").select("id,employee_code,name,department,role,level,reporting_manager_id,date_of_joining,date_of_birth,status").eq("status","active").order("employee_code");
  if(actor.role==="employee") query=query.eq("id",actor.employeeId); else if(actor.role==="manager") query=query.or(`id.eq.${actor.employeeId},reporting_manager_id.eq.${actor.employeeId}`);
  const result=await query;if(result.error)throw new Error(result.error.message);
  const rows=result.data as PerformanceEmployee[]; const managerIds=[...new Set(rows.map(row=>row.reporting_manager_id).filter(Boolean))] as string[];
  if(!managerIds.length)return rows; const managers=await actor.admin.from("employees").select("id,name").in("id",managerIds);if(managers.error)throw new Error(managers.error.message);
  const map=new Map((managers.data||[]).map(item=>[item.id,item]));return rows.map(row=>({...row,reporting_manager:row.reporting_manager_id?map.get(row.reporting_manager_id)||null:null}));
}

async function syncPayrollLopEvents(actor:Actor,year:number,employeeIds:string[]){
  if(!employeeIds.length)return;
  const metric=await actor.admin.from("performance_metric_definitions").select("id,default_score_delta").eq("code","lop").eq("active",true).maybeSingle();
  if(metric.error||!metric.data)return;
  const lopMetric=metric.data;
  const payroll=await actor.admin.from("payroll_entries").select("id,employee_id,payroll_month,lop_days,status").in("employee_id",employeeIds).in("status",["approved","locked","published"]).gte("payroll_month",`${year}-01-01`).lte("payroll_month",`${year}-12-31`).gt("lop_days",0);
  if(payroll.error)throw new Error(payroll.error.message);
  const rows=(payroll.data||[]).map(entry=>({employee_id:entry.employee_id,performance_year:year,metric_id:lopMetric.id,client_id:null,event_date:String(entry.payroll_month),description:`${Number(entry.lop_days)} LOP day${Number(entry.lop_days)===1?"":"s"} recorded in finalized payroll`,qualification_status:"qualified",score_delta:Number(lopMetric.default_score_delta||0),reason:"Automatically synchronized from finalized payroll",notes:null,evidence_url:null,source_type:"payroll",source_id:entry.id,updated_by:actor.userId}));
  if(rows.length){const synced=await actor.admin.from("performance_events").upsert(rows,{onConflict:"source_type,source_id",ignoreDuplicates:false});if(synced.error)throw new Error(synced.error.message);}
}

export async function loadPerformance(request:Request,yearInput:unknown):Promise<PerformanceData>{
  const actor=await performanceActor(request);const year=validYear(yearInput||new Date().getFullYear());const employees=await visibleEmployees(actor);const employeeIds=employees.map(item=>item.id);
  await syncPayrollLopEvents(actor,year,employeeIds);
  const [policyResult,metricResult,eventResult,reviewResult,commentResult,entryResult,clientResult,settingsResult]=await Promise.all([
    actor.admin.from("utilization_policies").select("*").order("level_group"),
    actor.admin.from("performance_metric_definitions").select("*").order("display_order"),
    employeeIds.length?actor.admin.from("performance_events").select("*,clients(id,name)").eq("performance_year",year).in("employee_id",employeeIds).order("event_date"):{data:[],error:null},
    employeeIds.length?actor.admin.from("performance_reviews").select("*").eq("performance_year",year).in("employee_id",employeeIds):{data:[],error:null},
    employeeIds.length?actor.admin.from("performance_comments").select("*").eq("performance_year",year).in("employee_id",employeeIds).order("created_at"):{data:[],error:null},
    loadAllBillableTimeEntries(actor,year,employeeIds),
    actor.admin.from("clients").select("id,name").eq("status","active").order("name"),
    actor.admin.from("performance_settings").select("*").eq("singleton_key",true).maybeSingle(),
  ]);
  const failure=policyResult.error||metricResult.error||eventResult.error||reviewResult.error||commentResult.error||entryResult.error||clientResult.error||settingsResult.error;if(failure)throw new Error(failure.message);
  const policies=policyResult.data as UtilizationPolicy[];const metrics=metricResult.data as PerformanceMetric[];
  const settings=(settingsResult.data||{singleton_key:true,policy_version:1,eligibility_rules:{minimumOverallScore:80,maximumEscalations:2},performance_categories:[]}) as PerformanceSettings;
  const allReviews=(reviewResult.data||[]).map(row=>({...row,employee:employees.find(employee=>employee.id===row.employee_id)})) as PerformanceReview[];
  const reviews=allReviews;
  const displayEmployees=employees;
  const displayEmployeeIds=new Set(displayEmployees.map(employee=>employee.id));
  const allEvents=(eventResult.data||[]).map(row=>({...row,metric:metrics.find(metric=>metric.id===row.metric_id),client:row.clients||null})).filter(event=>displayEmployeeIds.has(event.employee_id)) as PerformanceEvent[];
  const events=actor.role==="employee"?allEvents.filter(event=>event.metric?.category==="booster"):allEvents;
  const calculations:PerformanceData["calculations"]={};
  for(const employee of displayEmployees){const review=reviews.find(item=>item.employee_id===employee.id);if(review?.status==="finalized"&&review.snapshot?.calculation){calculations[employee.id]=review.snapshot.calculation as PerformanceData["calculations"][string];continue;}const monthly=Array(12).fill(0) as number[];for(const entry of entryResult.data||[]){if(entry.employee_id===employee.id)monthly[Number(String(entry.entry_date).slice(5,7))-1]+=Number(entry.hours||0);}calculations[employee.id]=calculatePerformance({policy:policyForLevel(employee.level,policies),monthlyBillableHours:monthly,events:allEvents.filter(event=>event.employee_id===employee.id),metrics,reviewFinalized:false,eligibilityRules:settings.eligibility_rules,performanceCategories:settings.performance_categories});}
  const comments=(commentResult.data||[]).filter(comment=>displayEmployeeIds.has(comment.employee_id));
  return {role:actor.role,employeeId:actor.employeeId,year,canAdminister:hasSuperAdminAccess(actor.role),employees:displayEmployees,metrics,policies,events,reviews,comments,calculations,clients:hasSuperAdminAccess(actor.role)?clientResult.data||[]:[],settings};
}

async function editableReview(actor:Actor,employeeId:string,year:number){const result=await actor.admin.from("performance_reviews").select("*").eq("employee_id",employeeId).eq("performance_year",year).eq("review_type","annual").maybeSingle();if(result.error)throw new Error(result.error.message);if(result.data?.status==="finalized")throw new Error("Finalized reviews are read-only. Reopen the review first.");return result.data;}

export async function createPerformanceEvent(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);performanceAdmin(actor.role);const year=validYear(body.performanceYear);const employeeId=String(body.employeeId||"");await editableReview(actor,employeeId,year);const metric=await actor.admin.from("performance_metric_definitions").select("*").eq("id",String(body.metricId||"")).single();if(metric.error)throw new Error(metric.error.message);if(metric.data.requires_client&&!body.clientId)throw new Error("This performance metric requires a client");const values={employee_id:employeeId,performance_year:year,metric_id:metric.data.id,client_id:body.clientId||null,event_date:String(body.eventDate||""),description:String(body.description||"").trim(),qualification_status:String(body.qualificationStatus||"qualified"),score_delta:Number(body.scoreDelta??metric.data.default_score_delta),evidence_url:String(body.evidenceUrl||"").trim()||null,notes:String(body.notes||"").trim()||null,reason:String(body.reason||"").trim()||null,policy_category:String(body.policyCategory||"").trim()||null,lost_client:Boolean(body.lostClient),refund_amount:body.refundAmount==null?null:Number(body.refundAmount),source_type:"manual",created_by:actor.userId,updated_by:actor.userId};if(!values.description||!/^\d{4}-\d{2}-\d{2}$/.test(values.event_date))throw new Error("Description and a valid event date are required");const inserted=await actor.admin.from("performance_events").insert(values).select("*").single();if(inserted.error)throw new Error(inserted.error.message);await audit(actor,{action:"performance_event_added",employeeId,year,metricId:metric.data.id,eventId:inserted.data.id,next:inserted.data});return inserted.data;}

export async function deletePerformanceEvent(request:Request,eventId:string){const actor=await performanceActor(request);performanceAdmin(actor.role);const previous=await actor.admin.from("performance_events").select("*").eq("id",eventId).single();if(previous.error)throw new Error(previous.error.message);if(previous.data.source_type==="payroll")throw new Error("Payroll-synchronized LOP events cannot be deleted manually");await editableReview(actor,previous.data.employee_id,previous.data.performance_year);const removed=await actor.admin.from("performance_events").delete().eq("id",eventId);if(removed.error)throw new Error(removed.error.message);await audit(actor,{action:"performance_event_deleted",employeeId:previous.data.employee_id,year:previous.data.performance_year,metricId:previous.data.metric_id,eventId,previous:previous.data});return {ok:true};}

export async function updatePerformanceEvent(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);performanceAdmin(actor.role);const eventId=String(body.eventId||"");const previous=await actor.admin.from("performance_events").select("*").eq("id",eventId).single();if(previous.error)throw new Error(previous.error.message);if(previous.data.source_type==="payroll")throw new Error("Payroll-synchronized LOP events cannot be edited manually");await editableReview(actor,previous.data.employee_id,previous.data.performance_year);const values={event_date:String(body.eventDate||previous.data.event_date),description:String(body.description??previous.data.description).trim(),qualification_status:String(body.qualificationStatus||previous.data.qualification_status),score_delta:Number(body.scoreDelta??previous.data.score_delta),client_id:body.clientId===undefined?previous.data.client_id:body.clientId||null,evidence_url:String(body.evidenceUrl??previous.data.evidence_url??"").trim()||null,notes:String(body.notes??previous.data.notes??"").trim()||null,reason:String(body.reason??previous.data.reason??"").trim()||null,policy_category:String(body.policyCategory??previous.data.policy_category??"").trim()||null,lost_client:body.lostClient===undefined?previous.data.lost_client:Boolean(body.lostClient),refund_amount:body.refundAmount===undefined?previous.data.refund_amount:Number(body.refundAmount),updated_by:actor.userId,updated_at:new Date().toISOString()};if(!values.description)throw new Error("Description is required");const updated=await actor.admin.from("performance_events").update(values).eq("id",eventId).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"performance_event_updated",employeeId:previous.data.employee_id,year:previous.data.performance_year,metricId:previous.data.metric_id,eventId,previous:previous.data,next:updated.data});return updated.data;}

export async function changeReviewStatus(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);const year=validYear(body.performanceYear);const employeeId=String(body.employeeId||"");const next=String(body.status||"");const isAdmin=hasSuperAdminAccess(actor.role);const employee=await actor.admin.from("employees").select("reporting_manager_id").eq("id",employeeId).single();if(employee.error)throw new Error(employee.error.message);if(!isAdmin&&!(actor.role==="manager"&&employee.data.reporting_manager_id===actor.employeeId))throw new Error("You cannot change this review");const existing=await actor.admin.from("performance_reviews").select("*").eq("employee_id",employeeId).eq("performance_year",year).eq("review_type","annual").maybeSingle();if(existing.error)throw new Error(existing.error.message);if(next==="reopened"){performanceAdmin(actor.role);const reason=String(body.reason||"").trim();if(existing.data?.status!=="finalized"||!reason)throw new Error("A finalized review and mandatory reopen reason are required");const updated=await actor.admin.from("performance_reviews").update({status:"reopened",reopened_at:new Date().toISOString(),reopened_by:actor.userId,reopen_reason:reason,updated_by:actor.userId}).eq("id",existing.data.id).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"review_reopened",reviewId:existing.data.id,employeeId,year,reason,previous:existing.data,next:updated.data});return updated.data;}
  if(next==="finalized"){performanceAdmin(actor.role);const data=await loadPerformance(request,year);const liveCalculation=data.calculations[employeeId];if(!liveCalculation)throw new Error("Performance calculation is unavailable");const calculation={...liveCalculation,eligibility:liveCalculation.eligibilityReasons.length?"not_eligible" as const:"eligible" as const};const employeeEvents=data.events.filter(item=>item.employee_id===employeeId);const eventReferences=employeeEvents.map(item=>item.id);const snapshot={employee:data.employees.find(item=>item.id===employeeId),calculation:{...calculation,scoredEvents:calculation.scoredEvents.map(item=>({id:item.id,metric_id:item.metric_id,appliedScore:item.appliedScore,scoringReason:item.scoringReason}))},eventReferences,recognitionTotal:calculation.boosterScore,penaltyTotal:calculation.penaltyScore,comments:data.comments.filter(item=>item.employee_id===employeeId),policy:calculation.policy,policyVersion:data.settings.policy_version,managerDecision:String(body.managerDecision||existing.data?.manager_decision||""),hrDecision:String(body.hrDecision||""),finalizedAt:new Date().toISOString()};const values={status:"finalized",snapshot,manager_decision:snapshot.managerDecision||null,hr_decision:snapshot.hrDecision||null,finalized_at:new Date().toISOString(),finalized_by:actor.userId,updated_by:actor.userId};const updated=existing.data?await actor.admin.from("performance_reviews").update(values).eq("id",existing.data.id).select("*").single():await actor.admin.from("performance_reviews").insert({employee_id:employeeId,performance_year:year,review_type:"annual",...values,created_by:actor.userId}).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"review_finalized",reviewId:updated.data.id,employeeId,year,next:snapshot});return updated.data;}
  if(!["draft","under_review"].includes(next))throw new Error("Unsupported review status");const values={status:next,updated_by:actor.userId,updated_at:new Date().toISOString()};const updated=existing.data?await actor.admin.from("performance_reviews").update(values).eq("id",existing.data.id).select("*").single():await actor.admin.from("performance_reviews").insert({employee_id:employeeId,performance_year:year,review_type:"annual",...values,created_by:actor.userId}).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"review_status_changed",reviewId:updated.data.id,employeeId,year,previous:existing.data,next:updated.data});return updated.data;}

export async function addPerformanceComment(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);const year=validYear(body.performanceYear);const employeeId=String(body.employeeId||"");const comment=String(body.comment||"").trim();if(!comment)throw new Error("Comment is required");const review=await actor.admin.from("performance_reviews").select("*").eq("employee_id",employeeId).eq("performance_year",year).eq("review_type","annual").maybeSingle();if(review.error||!review.data)throw new Error("Create the annual review before adding comments");if(review.data.status==="finalized")throw new Error("Finalized reviews are read-only");const employee=await actor.admin.from("employees").select("reporting_manager_id").eq("id",employeeId).single();const admin=hasSuperAdminAccess(actor.role);const manager=actor.role==="manager"&&employee.data?.reporting_manager_id===actor.employeeId;if(!admin&&!manager&&employeeId!==actor.employeeId)throw new Error("You cannot comment on this review");const commentType=admin?"admin":manager?"manager":"employee";const inserted=await actor.admin.from("performance_comments").insert({review_id:review.data.id,employee_id:employeeId,performance_year:year,author_employee_id:actor.employeeId,author_role:actor.role,comment_type:commentType,comment}).select("*").single();if(inserted.error)throw new Error(inserted.error.message);await audit(actor,{action:"performance_comment_added",reviewId:review.data.id,employeeId,year,next:{commentType}});return inserted.data;}

export async function savePerformancePolicy(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);performanceAdmin(actor.role);const previous=await actor.admin.from("utilization_policies").select("*").eq("level_group",String(body.levelGroup)).single();if(previous.error)throw new Error(previous.error.message);const fields={expected_percent:Number(body.expectedPercent),monthly_expected_hours:Number(body.monthlyExpectedHours),quarterly_expected_hours:Number(body.quarterlyExpectedHours),annual_expected_hours:Number(body.annualExpectedHours),minimum_percent:Number(body.minimumPercent),monthly_minimum_hours:Number(body.monthlyMinimumHours),quarterly_minimum_hours:Number(body.quarterlyMinimumHours),annual_minimum_hours:Number(body.annualMinimumHours),updated_by:actor.userId,updated_at:new Date().toISOString()};if(Object.values(fields).some(value=>typeof value==="number"&&(!Number.isFinite(value)||value<0)))throw new Error("Policy values must be valid non-negative numbers");const updated=await actor.admin.from("utilization_policies").update(fields).eq("level_group",String(body.levelGroup)).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"utilization_policy_changed",previous:previous.data,next:updated.data});return updated.data;}

export async function savePerformanceSettings(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);performanceAdmin(actor.role);const previous=await actor.admin.from("performance_settings").select("*").eq("singleton_key",true).single();if(previous.error)throw new Error(previous.error.message);const minimumOverallScore=Number(body.minimumOverallScore);const maximumEscalations=Number(body.maximumEscalations);const categories=Array.isArray(body.performanceCategories)?body.performanceCategories.map(item=>{const row=item as Record<string,unknown>;return{name:String(row.name||"").trim(),minimumScore:Number(row.minimumScore)}}):[];if(!Number.isFinite(minimumOverallScore)||minimumOverallScore<0||!Number.isInteger(maximumEscalations)||maximumEscalations<0)throw new Error("Eligibility values must be valid non-negative numbers");if(categories.length<2||categories.some(item=>!item.name||!Number.isFinite(item.minimumScore)||item.minimumScore<0))throw new Error("Performance categories require a name and valid minimum score");const values={eligibility_rules:{minimumOverallScore,maximumEscalations},performance_categories:categories,policy_version:Number(previous.data.policy_version||1)+1,updated_by:actor.userId,updated_at:new Date().toISOString()};const updated=await actor.admin.from("performance_settings").update(values).eq("singleton_key",true).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"performance_settings_changed",previous:previous.data,next:updated.data});return updated.data;}

export async function savePerformanceMetric(request:Request,body:Record<string,unknown>){const actor=await performanceActor(request);performanceAdmin(actor.role);const id=String(body.id||"");const values={name:String(body.name||"").trim(),code:String(body.code||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_"),category:String(body.category||"booster"),default_score_delta:Math.abs(Number(body.defaultScoreDelta||0)),requires_client:Boolean(body.requiresClient),active:body.active!==false,display_order:Number(body.displayOrder||0),updated_by:actor.userId,updated_at:new Date().toISOString()};if(!values.name||!values.code)throw new Error("Metric name and code are required");if(id){const previous=await actor.admin.from("performance_metric_definitions").select("*").eq("id",id).single();if(previous.error)throw new Error(previous.error.message);const updated=await actor.admin.from("performance_metric_definitions").update(values).eq("id",id).select("*").single();if(updated.error)throw new Error(updated.error.message);await audit(actor,{action:"performance_metric_updated",metricId:id,previous:previous.data,next:updated.data});return updated.data;}const inserted=await actor.admin.from("performance_metric_definitions").insert({...values,created_by:actor.userId}).select("*").single();if(inserted.error)throw new Error(inserted.error.message);await audit(actor,{action:"performance_metric_added",metricId:inserted.data.id,next:inserted.data});return inserted.data;}

export async function deletePerformanceMetric(request:Request,metricId:string){const actor=await performanceActor(request);performanceAdmin(actor.role);const metric=await actor.admin.from("performance_metric_definitions").select("*").eq("id",metricId).single();if(metric.error)throw new Error(metric.error.message);if(metric.data.core_metric)throw new Error("Core policy metrics cannot be deleted. Deactivate them instead.");const removed=await actor.admin.from("performance_metric_definitions").delete().eq("id",metricId);if(removed.error)throw new Error(removed.error.message);await audit(actor,{action:"performance_metric_deleted",metricId,previous:metric.data});return {ok:true};}
