import type { AssetRequestStatus } from "./workflow";
export type AssetCategory={id:string;name:string;description:string|null;active:boolean;display_order:number};
export type AssetRequestType={id:string;code:string;name:string;active:boolean;system_locked:boolean;display_order:number};
export type AssetItem={id:string;category_id:string;name:string;item_type:"durable_asset"|"accessory"|"consumable"|"stationery";stock_tracked:boolean;individually_tracked:boolean;current_stock:number;minimum_stock_level:number;requires_approval:boolean;active:boolean;display_order:number;category?:{name:string}|null};
export type EmployeeOption={id:string;employee_code:string;name:string;title?:string|null};
export type AssetRecord={id:string;item_id:string;brand:string|null;model:string|null;serial_number:string|null;asset_tag:string;condition:string;status:string;notes:string|null;item?:{name:string;item_type:string}|null};
export type AssetAssignment={id:string;asset_id:string;employee_id:string;request_id:string|null;issued_date:string;returned_date:string|null;condition_at_issue:string;condition_at_return:string|null;status:string;notes:string|null;asset?:AssetRecord|null;employee?:EmployeeOption|null};
export type AssetRequest={id:string;request_code:string;employee_id:string;category_id:string;item_id:string;request_type_id:string;quantity_requested:number;quantity_approved:number|null;reason:string;comments:string|null;existing_asset_id:string|null;selected_asset_id:string|null;status:AssetRequestStatus;admin_comment:string|null;previous_id_deactivated:boolean;approved_at:string|null;issued_at:string|null;created_at:string;employee?:EmployeeOption|null;category?:{name:string}|null;item?:{name:string;item_type:string;stock_tracked:boolean;current_stock:number}|null;request_type?:{name:string;code:string}|null;existing_asset?:{asset_tag:string;brand:string|null;model:string|null}|null};
export type AssetsPayload={role:string;employeeId:string;canAdminister:boolean;categories:AssetCategory[];requestTypes:AssetRequestType[];items:AssetItem[];assets:AssetRecord[];assignments:AssetAssignment[];requests:AssetRequest[];employees:EmployeeOption[];history:Array<Record<string,unknown>>;audit:Array<Record<string,unknown>>};

