begin;
insert into public.terms_templates(name,version,effective_from,structured_sections,active,source_reference)
values('Despacho Terms of Service','TOS-2026-04','2026-04-02',(
  $terms$[{"title":"Agreement Introduction","content":"These terms of service (\u201cTerms of Service\u201d) are made and entered into as of {{EFFECTIVE_DATE}} (\u201cEffective Date\u201d) between Despacho Inc. (hereinafter referred as \"Despacho\") and {{CUSTOMER_NAME}} (hereinafter referred as \"Customer\"). This agreement governs the provision of services by Despa$terms$
  || $terms$cho (\"Despacho\") to its Customers (\"Customer\").\n\nNOW THIS AGREEMENT WITNESSETH AS FOLLOWS;"},{"title":"Purpose of Agreement","content":"During the term hereof, Despacho agrees to provide agreed remote executive assistance services (\"Services\") to Customer or its affiliates. The purpose of this agreement is to establish the fundamental terms$terms$
  || $terms$ and conditions that will govern the parties\u2019 business relationship and that will be applicable to any service provided by Despacho."},{"title":"2. Scope of Service","content":"Despacho will provide services to customer as described in the Work Order(s) which will be considered as exhibits to this Agreement and which will be governed by all te$terms$
  || $terms$rms and conditions set forth in this agreement. The Work Order(s) will define the specific Services to be performed by Despacho, the schedule or term, the applicable rates and charges therefore, and other appropriate terms and conditions. All items prepared or required to be delivered under the Work Order(s) are collectively referred to herein as t$terms$
  || $terms$he \"Deliverables\"."},{"title":"3. Provision of Service","content":"Despacho will provide the agreed service in accordance with the specifications and schedule set forth in the Work order, in a timely and professional manner by skilled personnel, will conform to the industry standards quality, in compliance with all applicable laws or regulations.$terms$
  || $terms$ Despacho will not cause or create any violation or infringement of any copyright, patent, trademark, other intellectual property right, or any privacy, contractual, or other right of any person or entity."},{"title":"4. Term & Termination","content":"This Terms of Service shall be effective from the effective date mentioned above and shall be vali$terms$
  || $terms$d till the completion of the Customer\u2019s engagement with Despacho or until terminated by either party with written notice as specified herein below.\n\nTermination with cause: Either party may terminate this Terms of Service for cause, in the event the other party has failed to perform any obligation required to be performed under this Terms of$terms$
  || $terms$ Service and such failure is not corrected within thirty (30) days from receipt of written notice advising of such failure from the other party.\n\nTermination without cause: Either party may terminate this Terms of Service without any cause after giving 30 days prior written notice to the other party. Upon termination each party shall return to th$terms$
  || $terms$e other all applicable Confidential Information."},{"title":"5. Payment","content":"The Customer shall pay the project fees as per the schedule mentioned in the Work Order and the payment terms as described in the relevant Work Order(s) will be adhered to."},{"title":"6. Intellectual Property","content":"Despacho acknowledges that the work or Deliv$terms$
  || $terms$erable is being created as a \u201cwork made for hire\u201d and, at all stages of development, the work or deliverables shall be and remain the sole and exclusive property of the Customer. Despacho agrees to transfer and assign, to the Customer and its designees, without further compensation, the entire right, title and interest throughout the worl$terms$
  || $terms$d in and to: (a) all technical information first produced by Despacho in the performance of this Terms of Service; (b) all intellectual property resulting from Despacho\u2019s activities under this Terms of Service; (c) all intellectual property relating to any deliverables under this Terms of Service; and (d) creations and inventions that are othe$terms$
  || $terms$rwise made through the use of Customer\u2019s affiliates\u2019 equipment, supplies, facilities, materials and/or proprietary information.\n\nEach party retains sole and exclusive ownership of any intellectual property already existing as of the Effective Date and of any derivative works of such intellectual property created after the Effective Date$terms$
  || $terms$; provided that such derivative work (a) does not arise from the Confidential Information of the other party; and/or (b) is not created specifically for Customer by Despacho.\n\nExcept as provided otherwise in this Agreement, all data, results, ideas, discoveries, inventions, reports and works of authorship, whether or not patentable or subject to $terms$
  || $terms$copyright, which may be made, written, conceived or reduced to practice by Despacho or any third-party, that does not arise from Customer\u2019s Confidential Information and/or that is not created specifically for Customer by Despacho will be owned solely by Despacho.\n\nExcept as provided otherwise in this Agreement, all data, results, ideas, disc$terms$
  || $terms$overies, inventions, reports and works of authorship, whether or not patentable or subject to copyright, which may be made, written, conceived or reduced to practice by Despacho or by Despacho together with Customer or any third-party, arising from Customer\u2019s Confidential Information and/or that is created specifically for Customer by Despacho$terms$
  || $terms$ will be owned solely by Customer."},{"title":"7. Confidentiality & Nondisclosure","content":"\u201cConfidential Information\u201d means information related to the business (including third party information), which (i) is subject to privacy rules and regulations and/or derives economic value, actual or potential, from not being generally known to $terms$
  || $terms$or readily ascertainable by other persons who can obtain economic value from the disclosure or use of the information, (ii) is the subject of efforts that are reasonable under the circumstances to maintain the secrecy of the information, and (iii) is identified by the \u201cCustomer\u201d as \u201cConfidential\u201d and/or \u201cProprietary\u201d, $terms$
  || $terms$or which, under all of the circumstances, ought reasonably to be treated as confidential and/or proprietary under this Terms of Service.\n\nConfidential Information shall not include information which, as Despacho can prove, (i) is now or subsequently becomes generally known or available by publication, commercial use or otherwise, through no fault$terms$
  || $terms$ of the Despacho, (ii) is known by the Despacho at the time of disclosure, or (iii) is lawfully obtained by the Despacho without violation of a confidentiality obligation (iv) is developed by the Despacho independent of any use of and/or access to the Discloser\u2019s Information.\n\nNeither Customer nor Despacho shall disclose to a third-party Con$terms$
  || $terms$fidential Information of the other party. Despacho shall use the same degree of care and caution as it uses to protect the confidentiality of its own confidential information of like nature, but not less than a reasonable degree of care, to maintain in confidence the Confidential Information of the Customer, and to ensure that Despacho\u2019s \"Emp$terms$
  || $terms$loyees\" (as defined herein) maintain confidence of the Confidential Information. The foregoing obligations shall not apply to any information that is required to be disclosed by law or subpoena. The confidentiality obligation set forth herein shall survive the expiration or termination of this Agreement for any reason whatsoever, remaining valid a$terms$
  || $terms$nd in full force for three (3) years after the initial disclosure date of each respective item of Confidential Information disclosed hereunder."},{"title":"8. Use of Customer Property and Materials","content":"In order to facilitate the efficient delivery of Services, Customer may provide property, material time to time, including for example and w$terms$
  || $terms$ithout limitation licensed software, telephone equipment. Despacho warrants that all customer property is used exclusively in connection with the Services under this Agreement and not for any other purpose."},{"title":"9. Return of Customer Property and Materials","content":"Upon termination or expiration of this Agreement and upon Customer\u2019s $terms$
  || $terms$request at any other time, Despacho shall in a manner approved Customer, and at Customer\u2019s expenses, promptly deliver all materials and property to the Customer."},{"title":"10. Indemnification","content":"Despacho shall indemnify, defend, and hold harmless Customer, its affiliates, directors, officers, employees, and agents (collectively, \"I$terms$
  || $terms$ndemnified Parties\") from and against any and all claims, demands, losses, liabilities, damages, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) any breach of this Agreement by Contractor; or (b) any negligence, willful misconduct, or other wrongful act or omission of Contractor or its employees, agent$terms$
  || $terms$s, or subcontractors in connection with the performance of this Agreement. This indemnification obligation shall survive the termination or expiration of this Agreement.\"\n\nCustomer shall indemnify, defend, and hold harmless Despacho, its affiliates, directors, officers, employees, and agents (collectively, \"Indemnified Parties\") from and again$terms$
  || $terms$st any and all claims, demands, losses, liabilities, damages, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) any breach of this Agreement by Customer; or (b) any negligence, willful misconduct, or other wrongful act or omission of Customer or its employees, agents, or subcontractors in connection with $terms$
  || $terms$the performance of this Agreement. This indemnification obligation shall survive the termination or expiration of this Agreement.\""},{"title":"11. Limitation of Liability","content":"Other than in the event of gross negligence or willful misconduct:\n\nno event shall either party be liable for any indirect, incidental, special or consequential dam$terms$
  || $terms$ages, including without limitation damages for loss of profits, data or use, errors or omissions, incurred by either party or any third party, whether in an action in contract or tort, even if the other party has been advised of the possibility of such damages; and\n\nDespacho\u2019s aggregate and cumulative liability for damages on all accounts he$terms$
  || $terms$reunder shall in no event exceed the amount of fees received from the Customer in the last six (6) months under the relevant Work Order giving rise to the liability."},{"title":"12. Non-Solicitation","content":"During the term of the Customer\u2019s project with Despacho and for two (2) years period from the date of completion of Customer\u2019s la$terms$
  || $terms$st Project with Despacho, each party agrees that it will not (through itself, affiliates, principals, or other related parties) solicit for employment, employ, consult with, utilize the services of, or in any other manner induce any employees or give reference (personally or on any public platform) of any employees of the other party including the $terms$
  || $terms$former employees who was engaged or involved in any manner with that particular Customer\u2019s project to perform services for such party or any person or entity related thereto."},{"title":"13. Independent Contractor","content":"Despacho is and will remain as an independent contractor in its relationship with Customer. Nothing in this Terms of Se$terms$
  || $terms$rvice shall be deemed to have created a partnership, or joint venture or a contract of employment between Despacho and Customer."},{"title":"14. Further Documentation","content":"If any other agreements or Work Order(s) are necessary to enforce the intent of this document, both parties agree to execute such provisions as and when the need arises."}$terms$
  || $terms$,{"title":"15. Force Majeure","content":"Despacho and Customer shall mutually have no liability for any failure beyond its reasonable control and without its fault or negligence including, but not limited to, acts of God, severe weather, etc."},{"title":"16. Severability","content":"If any of these terms and conditions are held to be unenforceable $terms$
  || $terms$or against public policy, by a competent court or arbitration, then that term alone shall be removed from this document and the remainder of the Terms of Service shall stay in full force and effect."},{"title":"17. Amendment","content":"This Agreement may be amended or modified only by a written instrument, mutually agreed by both the parties and s$terms$
  || $terms$igned by a duly authorized representative of the parties. This Agreement supersedes and replaces any and all previous agreements between the parties."},{"title":"18. Governing laws and jurisdiction:","content":"This Agreement shall be governed by and construed and enforced in accordance with the laws of Alberta, Canada excluding that body of law pe$terms$
  || $terms$rtaining to conflict of law, and the parties hereto agree to submit to the exclusive jurisdiction of the courts of Alberta for any disputes arising out of the subject matter."},{"title":"19. Dispute Resolution","content":"Any disputes arising out of or in connection with the Terms of Service shall be first attempted to be settled through discussion$terms$
  || $terms$ and negotiation between the heads of the respective organizations. If a settlement is not arrived at within thirty (30) days, the dispute shall be referred to Mediation. The parties will select a mediator by their mutual agreement, within 15 days. The cost of the Mediation shall be divided equally among the parties involved. Once a settlement has $terms$
  || $terms$been reached, a mediation agreement shall be drawn up. If parties fail to come into any settlement through mediation, parties will have the right to refer the dispute to the court."},{"title":"20. Acknowledgment","content":"This Terms of Service together with the Work Order(s) and further documents as necessary, set forth the entire agreement and u$terms$
  || $terms$nderstanding between the parties relating to the subject matter and supersedes all prior discussions, oral or in writing, between the parties.\n\nThe parties have fully read and agree to the terms and conditions of this Terms of Service."}]$terms$
)::jsonb,true,'Approved Despacho legal baseline for versioned Work Orders')
on conflict(version) do update set name=excluded.name,effective_from=excluded.effective_from,structured_sections=excluded.structured_sections,active=excluded.active,source_reference=excluded.source_reference,updated_at=now();
commit;
