import { createElement, type ReactElement } from "react";
import { renderToBuffer, type DocumentProps } from "@react-pdf/renderer";
import { PerformanceReportPdf } from "@/components/performance/PerformanceReportPdf";
import { loadCompanyLogo, loadCompanySettings } from "@/lib/settings/companySettings";
import { loadPerformance, performanceActor } from "@/lib/performance/server";
import { protectEmployeePdf } from "@/lib/pdf/employeePdfSecurity";
import { hasSuperAdminAccess } from "@/lib/roles";

export async function GET(request:Request){try{const actor=await performanceActor(request);const url=new URL(request.url);const employeeId=url.searchParams.get("employeeId")||"";const year=Number(url.searchParams.get("year"));if(!employeeId||!Number.isInteger(year))throw new Error("Employee and performance year are required");const employeeResult=await actor.admin.from("employees").select("id,employee_code,name,department,role,level,reporting_manager_id,date_of_joining,date_of_birth,status").eq("id",employeeId).single();if(employeeResult.error)throw new Error(employeeResult.error.message);const employee=employeeResult.data;if(!hasSuperAdminAccess(actor.role)&&actor.role!=="admin"&&actor.employeeId!==employee.id&&!(actor.role==="manager"&&employee.reporting_manager_id===actor.employeeId))throw new Error("Forbidden");const data=await loadPerformance(request,year);const calculation=data.calculations[employeeId];if(!calculation)throw new Error("Performance calculation is unavailable");const currentReview=data.reviews.find(item=>item.employee_id===employeeId);const reviewStatus=currentReview?.status==="finalized"?"Review Finalized":currentReview?.status==="under_review"||currentReview?.status==="reopened"?"Review Started":"Review Not Started";const manager=employee.reporting_manager_id?await actor.admin.from("employees").select("id,name").eq("id",employee.reporting_manager_id).maybeSingle():{data:null,error:null};const company=await loadCompanySettings(actor.admin);const logo=await loadCompanyLogo({...company,invoice_logo_url:"/despacho-logo-full.png"});const document=createElement(PerformanceReportPdf,{logoSrc:logo.dataUrl,year,employee:{...employee,reporting_manager:manager.data||null},calculation,events:data.events.filter(item=>item.employee_id===employeeId),comments:data.comments.filter(item=>item.employee_id===employeeId),reviewStatus}) as ReactElement<DocumentProps>;const generatedPdf=await renderToBuffer(document);const pdf=await protectEmployeePdf({admin:actor.admin,pdfBytes:generatedPdf,employee:{employeeCode:employee.employee_code,employeeName:employee.name,dateOfBirth:employee.date_of_birth},documentType:"performance"});return new Response(new Uint8Array(pdf),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="Performance_Report_${employee.employee_code}_${year}.pdf"`,"Cache-Control":"private, no-store"}});}catch(cause){const message=cause instanceof Error?cause.message:"Unable to generate performance report";return Response.json({error:message},{status:message==="Unauthorized"?401:400});}}
